spring:
  application:
    name: SpringAILearning
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
        # model: qwen3.5-flash
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024 # 向量纬度，设置越大计算量就越大，结果越精准。根据官网介绍进行配置
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
        options:
          temperature: 0.8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringAILearning260311?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456
logging:
  level:
    org.springframework.ai: debug # AI对话的日志级别
    com.yuanyu.ai: debug # 本项目的日志级别